[project]
name = "ai-application-testing"
version = "0.1.0"
description = "code and documentation for the AI Alliance user guide and tools for 'Testing Generative AI Applications'."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "levenshtein>=0.27.3",
    "litellm>=1.76.2",
    "openai>=1.106.1",
]
